---
variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - scan_and_wait

gitleaks:
  tags:
    - secret-scanning
  stage: scan_and_wait
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.24.0-mega
    entrypoint: [""]
  script:
    - git fetch origin $CI_DEFAULT_BRANCH:$CI_DEFAULT_BRANCH
    - gitleaks git --verbose --redact -c .gitleaks/gitleaks.toml --log-opts="$CI_DEFAULT_BRANCH..$CI_COMMIT_SHA"

wait_for_jenkins:
  stage: scan_and_wait
  script:
    - echo "Waiting for Jenkins..."
    - sleep 300 # Wait 5 minutes for Jenkins
